### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ifeoluwajoshua** [Mastersam07/livechat#3]
I got this error today [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method beginChat on channel livechat)
E/flutter ( 6132): #0      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:159
E/flutter ( 6132): <asynchronous suspension>
E/flutter ( 6132): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:334
E/flutter ( 6132): #2      Livechat.beginChat  (package:livechat/livechat.dart:17:20)
E/flutter ( 6132): #3      _MyHomePageState.build.<anonymous closure>

**Comment by Mastersam07** [comment]
- Which version of the plugin are you using?
- You added the plugin and hot restarted or reloaded?

The plugin works as intended. The error probably appears because the addition of the plugin was followed by hot restart or hot reload rather than full restart. This means the plugin's platform-specific code is not built into the app.

Workaround: stop the app and restart it after adding a plugin...... Let me know if this fixes it.

Other helpful link(s): [Restart is needed after adding a plugin dependency](https://github.com/flutter/website/pull/1038)

**Comment by ifeoluwajoshua** [comment]
i tried it but it loads for some seconds and stops with couldnt load chat,
and doesnt reload

**Comment by Mastersam07** [comment]
Can you provide a screenshot of what you are seeing?

Also, are you using an emulator?

**Comment by ifeoluwajoshua** [comment]
no i am using a physical device

**Comment by ifeoluwajoshua** [comment]
is the groupid something i am to get  from livechat.com ?

**Comment by Mastersam07** [comment]
Yes. You are to get the credentials from livechat.com(GROUP_ID and LICENSE_NO) which you would pass to Livechat.beginChat(LICENSE_NO, GROUP_ID, VISITOR_NAME, VISITOR_EMAIL);

**Comment by ifeoluwajoshua** [comment]
worked thanks
